name = "algo-backend"
main = "main.py"
compatibility_date = "2024-09-25"
compatibility_flags = ["python_workers"]

[vars]
# SUPABASE_URL = "https://your-supabase-url.supabase.co"
# SUPABASE_KEY = "your-supabase-key"
